openapi: 3.0.0
info:
  title: Update exception list item API endpoint
  version: '2023-10-31'
paths:
  /api/exception_lists/items:
    put:
      x-labels: [serverless, ess]
      operationId: UpdateExceptionListItem
      x-codegen-enabled: true
      summary: Update an exception list item
      description: Update an exception list item using the `id` or `item_id` field.
      requestBody:
        description: Exception list item's properties
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemId'
                  description: Either `id` or `item_id` must be specified
                item_id:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemHumanId'
                  description: Either `id` or `item_id` must be specified
                list_id:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListHumanId'
                type:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemType'
                name:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemName'
                description:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemDescription'
                entries:
                  $ref: '../model/exception_list_item_entry.schema.yaml#/components/schemas/ExceptionListItemEntryArray'
                namespace_type:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionNamespaceType'
                  default: 'single'
                os_types:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemOsTypeArray'
                  default: []
                tags:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemTags'
                meta:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemMeta'
                expire_time:
                  $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItemExpireTime'
                comments:
                  $ref: '#/components/schemas/UpdateExceptionListItemCommentArray'
                  default: []
                _version:
                  type: string
                  description: The version id, normally returned by the API when the item was retrieved. Use it ensure updates are done against the latest version.
              required:
                - type
                - name
                - description
                - entries
            example:
              comments: []
              description: Updated description
              entries:
                - field: host.name
                  type: match
                  value: rock01
                  operator: included
              item_id: simple_list_item
              name: Updated name
              namespace_type: single
              tags: []
              type: simple
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../model/exception_list_common.schema.yaml#/components/schemas/ExceptionListItem'
              examples:
                simpleListItem:
                  value:
                    id: 459c5e7e-f8b2-4f0b-b136-c1fc702f72da
                    item_id: simple_list_item
                    list_id: simple_list
                    type: simple
                    name: Updated name
                    description: Updated description
                    entries:
                      - type: match
                        field: host.name
                        value: rock01
                        operator: included
                    namespace_type: single
                    os_types: []
                    tags: []
                    comments: []
                    _version: WzEyLDFd
                    tie_breaker_id: ad0754ff-7b19-49ca-b73e-e6aff6bfa2d0
                    created_at: 2025-01-07T21:12:25.512Z
                    created_by: elastic
                    updated_at: 2025-01-07T21:34:50.233Z
                    updated_by: elastic
        400:
          description: Invalid input data response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
                  - $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
              examples:
                badRequest:
                  value:
                    statusCode: 400
                    error: Bad Request
                    message: '[request body]: item_id: Expected string, received number'
        401:
          description: Unsuccessful authentication response
          content:
            application/json:
              schema:
                $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
              examples:
                unauthorized:
                  value:
                    statusCode: 401
                    error: Unauthorized
                    message: '[security_exception\n\tRoot causes:\n\t\tsecurity_exception: unable to authenticate user [elastic] for REST request [/_security/_authenticate]]: unable to authenticate user [elastic] for REST request [/_security/_authenticate]'
        403:
          description: Not enough privileges response
          content:
            application/json:
              schema:
                $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
              examples:
                forbidden:
                  value:
                    statusCode: 403
                    error: Forbidden
                    message: 'API [PUT /api/exception_lists/items] is unauthorized for user, this action is granted by the Kibana privileges [lists-all]'
        404:
          description: Exception list item not found response
          content:
            application/json:
              schema:
                $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
              examples:
                notFound:
                  value:
                    message: 'exception list item item_id: \"foo\" does not exist'
                    status_code: 404
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
              examples:
                serverError:
                  value:
                    message: Internal Server Error
                    status_code: 500

components:
  x-codegen-enabled: true
  schemas:
    UpdateExceptionListItemComment:
      type: object
      properties:
        id:
          $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/primitives.schema.yaml#/components/schemas/NonEmptyString'
        comment:
          $ref: '../../../../../../../src/platform/packages/shared/kbn-openapi-common/schemas/primitives.schema.yaml#/components/schemas/NonEmptyString'
      required:
        - comment

    UpdateExceptionListItemCommentArray:
      type: array
      items:
        $ref: '#/components/schemas/UpdateExceptionListItemComment'
