openapi: 3.0.0
info:
  title: Set alert tags API endpoint
  version: '2023-10-31'
paths:
  /api/detection_engine/signals/tags:
    post:
      x-labels: [serverless, ess]
      operationId: SetAlertTags
      x-codegen-enabled: true
      summary: Add and remove detection alert tags
      description: |
        And tags to detection alerts, and remove them from alerts.
        > info
        > You cannot add and remove the same alert tag in the same request.
      tags:
        - Alerts API
      requestBody:
        description: An object containing tags to add or remove and alert ids the changes will be applied
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  $ref: '../../../model/alert.schema.yaml#/components/schemas/AlertIds'
                tags:
                  $ref: '#/components/schemas/SetAlertTags'
              required:
                - ids
                - tags
            examples:
              add:
                value:
                  tags:
                    tags_to_add: ['Duplicate']
                    tags_to_remove: []
                  ids: ['549c7129c76cbd554aba1bd638f8a49dde95088f5832e50218358e7eca1cf16e']
              remove:
                value:
                  tags:
                    tags_to_add: []
                    tags_to_remove: ['Duplicate']
                  ids: ['549c7129c76cbd554aba1bd638f8a49dde95088f5832e50218358e7eca1cf16e']
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                description: Elasticsearch update by query response
              examples:
                success:
                  value:
                    took: 68,
                    timed_out: false,
                    total: 1,
                    updated: 1,
                    deleted: 0,
                    batches: 1,
                    version_conflicts: 0,
                    noops: 0,
                    retries:
                      bulk: 0,
                      search: 0
                    throttled_millis: 0,
                    requests_per_second: -1,
                    throttled_until_millis: 0,
                    failures: []
        400:
          description: Invalid input data response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '../../../model/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
                  - $ref: '../../../model/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
        401:
          description: Unsuccessful authentication response
          content:
            application/json:
              schema:
                $ref: '../../../model/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '../../../model/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'

components:
  schemas:
    SetAlertTags:
      description: Object with list of tags to add and remove.
      type: object
      properties:
        tags_to_add:
          $ref: '../../../model/alert.schema.yaml#/components/schemas/AlertTags'
        tags_to_remove:
          $ref: '../../../model/alert.schema.yaml#/components/schemas/AlertTags'
      required:
        - tags_to_add
        - tags_to_remove
