openapi: 3.0.3
info:
  description: >-
    You can create Timelines and Timeline templates via the API, as well as
    import new Timelines from an ndjson file.
  title: Security Timeline API (Elastic Cloud and self-hosted)
  version: '2023-10-31'
servers:
  - url: http://{kibana_host}:{port}
    variables:
      kibana_host:
        default: localhost
      port:
        default: '5601'
paths:
  /api/note:
    delete:
      description: Delete a note from a Timeline using the note ID.
      operationId: DeleteNote
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - nullable: true
                  type: object
                  properties:
                    noteId:
                      type: string
                  required:
                    - noteId
                - nullable: true
                  type: object
                  properties:
                    noteIds:
                      items:
                        type: string
                      nullable: true
                      type: array
                  required:
                    - noteIds
        description: The ID of the note to delete.
        required: true
      responses:
        '200':
          description: Indicates the note was successfully deleted.
      summary: Delete a note
      tags:
        - Security Timeline API
        - access:securitySolution
    get:
      description: Get all notes for a given document.
      operationId: GetNotes
      parameters:
        - in: query
          name: documentIds
          schema:
            $ref: '#/components/schemas/DocumentIds'
        - in: query
          name: savedObjectIds
          schema:
            $ref: '#/components/schemas/SavedObjectIds'
        - in: query
          name: page
          schema:
            nullable: true
            type: string
        - in: query
          name: perPage
          schema:
            nullable: true
            type: string
        - in: query
          name: search
          schema:
            nullable: true
            type: string
        - in: query
          name: sortField
          schema:
            nullable: true
            type: string
        - in: query
          name: sortOrder
          schema:
            nullable: true
            type: string
        - in: query
          name: filter
          schema:
            nullable: true
            type: string
        - in: query
          name: createdByFilter
          schema:
            nullable: true
            type: string
        - in: query
          name: associatedFilter
          schema:
            $ref: '#/components/schemas/AssociatedFilterType'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNotesResult'
          description: Indicates the requested notes were returned.
      summary: Get notes
      tags:
        - Security Timeline API
        - access:securitySolution
    patch:
      description: Add a note to a Timeline or update an existing note.
      operationId: PersistNoteRoute
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  $ref: '#/components/schemas/BareNote'
                  description: The note to add or update.
                noteId:
                  description: The `savedObjectId` of the note
                  example: 709f99c6-89b6-4953-9160-35945c8e174e
                  nullable: true
                  type: string
                version:
                  description: The version of the note
                  example: WzQ2LDFd
                  nullable: true
                  type: string
              required:
                - note
        description: The note to add or update, along with additional metadata.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseNote'
          description: Indicates the note was successfully created.
      summary: Add or update a note
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/pinned_event:
    patch:
      description: Pin/unpin an event to/from an existing Timeline.
      operationId: PersistPinnedEventRoute
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId:
                  description: The `_id` of the associated event for this pinned event.
                  example: d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bc
                  type: string
                pinnedEventId:
                  description: The `savedObjectId` of the pinned event you want to unpin.
                  example: 10r1929b-0af7-42bd-85a8-56e234f98h2f3
                  nullable: true
                  type: string
                timelineId:
                  description: >-
                    The `savedObjectId` of the timeline that you want this
                    pinned event unpinned from.
                  example: 15c1929b-0af7-42bd-85a8-56e234cc7c4e
                  type: string
              required:
                - eventId
                - timelineId
        description: The pinned event to add or unpin, along with additional metadata.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistPinnedEventResponse'
          description: >-
            Indicates the event was successfully pinned to or unpinned from the
            Timeline.
      summary: Pin/unpin an event
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline:
    delete:
      description: Delete one or more Timelines or Timeline templates.
      operationId: DeleteTimelines
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                savedObjectIds:
                  description: >-
                    The list of IDs of the Timelines or Timeline templates to
                    delete
                  example:
                    - 15c1929b-0af7-42bd-85a8-56e234cc7c4e
                  items:
                    type: string
                  type: array
                searchIds:
                  description: >-
                    Saved search IDs that should be deleted alongside the
                    timelines
                  example:
                    - 23f3-43g34g322-e5g5hrh6h-45454
                    - 6ce1b592-84e3-4b4a-9552-f189d4b82075
                  items:
                    type: string
                  type: array
              required:
                - savedObjectIds
        description: The IDs of the Timelines or Timeline templates to delete.
        required: true
      responses:
        '200':
          description: Indicates the Timeline was successfully deleted.
      summary: Delete Timelines or Timeline templates
      tags:
        - Security Timeline API
        - access:securitySolution
    get:
      description: Get the details of an existing saved Timeline or Timeline template.
      operationId: GetTimeline
      parameters:
        - description: The `savedObjectId` of the template timeline to retrieve
          in: query
          name: template_timeline_id
          schema:
            type: string
        - description: The `savedObjectId` of the Timeline to retrieve.
          in: query
          name: id
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineResponse'
          description: Indicates that the (template) Timeline was found and returned.
      summary: Get Timeline or Timeline template details
      tags:
        - Security Timeline API
        - access:securitySolution
    patch:
      description: >-
        Update an existing Timeline. You can update the title, description, date
        range, pinned events, pinned queries, and/or pinned saved queries of an
        existing Timeline.
      operationId: PatchTimeline
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                timeline:
                  $ref: '#/components/schemas/SavedTimeline'
                  description: >-
                    The timeline object of the Timeline or Timeline template
                    that you’re updating.
                timelineId:
                  description: >-
                    The `savedObjectId` of the Timeline or Timeline template
                    that you’re updating.
                  example: 15c1929b-0af7-42bd-85a8-56e234cc7c4e
                  nullable: true
                  type: string
                version:
                  description: >-
                    The version of the Timeline or Timeline template that you’re
                    updating.
                  example: WzE0LDFd
                  nullable: true
                  type: string
              required:
                - timelineId
                - version
                - timeline
        description: The Timeline updates, along with the Timeline ID and version.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistTimelineResponse'
          description: Indicates that the Timeline was successfully updated.
        '405':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: update timeline error
                    type: string
                  statusCode:
                    example: 405
                    type: number
          description: >-
            Indicates that the user does not have the required access to create
            a Timeline.
      summary: Update a Timeline
      tags:
        - Security Timeline API
        - access:securitySolution
    post:
      description: Create a new Timeline or Timeline template.
      operationId: CreateTimelines
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/TimelineStatus'
                  nullable: true
                templateTimelineId:
                  description: A unique identifier for the Timeline template.
                  example: 6ce1b592-84e3-4b4a-9552-f189d4b82075
                  nullable: true
                  type: string
                templateTimelineVersion:
                  description: Timeline template version number.
                  example: 12
                  nullable: true
                  type: number
                timeline:
                  $ref: '#/components/schemas/SavedTimeline'
                timelineId:
                  description: A unique identifier for the Timeline.
                  example: 6ce1b592-84e3-4b4a-9552-f189d4b82075
                  nullable: true
                  type: string
                timelineType:
                  $ref: '#/components/schemas/TimelineType'
                  nullable: true
                version:
                  nullable: true
                  type: string
              required:
                - timeline
        description: >-
          The required Timeline fields used to create a new Timeline, along with
          optional fields that will be created if not provided.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistTimelineResponse'
          description: Indicates the Timeline was successfully created.
        '405':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: update timeline error
                    type: string
                  statusCode:
                    example: 405
                    type: number
          description: Indicates that there was an error in the Timeline creation.
      summary: Create a Timeline or Timeline template
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_copy:
    get:
      description: |
        Copies and returns a timeline or timeline template.
      operationId: CopyTimeline
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                timeline:
                  $ref: '#/components/schemas/SavedTimeline'
                timelineIdToCopy:
                  type: string
              required:
                - timeline
                - timelineIdToCopy
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistTimelineResponse'
          description: Indicates that the timeline has been successfully copied.
      summary: Copies timeline or timeline template
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_draft:
    get:
      description: >-
        Get the details of the draft Timeline  or Timeline template for the
        current user. If the user doesn't have a draft Timeline, an empty
        Timeline is returned.
      operationId: GetDraftTimelines
      parameters:
        - in: query
          name: timelineType
          required: true
          schema:
            $ref: '#/components/schemas/TimelineType'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistTimelineResponse'
          description: Indicates that the draft Timeline was successfully retrieved.
        '403':
          content:
            application:json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: number
          description: >-
            If a draft Timeline was not found and we attempted to create one, it
            indicates that the user does not have the required permissions to
            create a draft Timeline.
        '409':
          content:
            application:json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: number
          description: >-
            This should never happen, but if a draft Timeline was not found and
            we attempted to create one, it indicates that there is already a
            draft Timeline with the given `timelineId`.
      summary: Get draft Timeline or Timeline template details
      tags:
        - Security Timeline API
        - access:securitySolution
    post:
      description: >
        Create a clean draft Timeline or Timeline template for the current user.

        > info

        > If the user already has a draft Timeline, the existing draft Timeline
        is cleared and returned.
      operationId: CleanDraftTimelines
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                timelineType:
                  $ref: '#/components/schemas/TimelineType'
              required:
                - timelineType
        description: >-
          The type of Timeline to create. Valid values are `default` and
          `template`.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistTimelineResponse'
          description: >-
            Indicates that the draft Timeline was successfully created. In the
            event the user already has a draft Timeline, the existing draft
            Timeline is cleared and returned.
        '403':
          content:
            application:json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: number
          description: >-
            Indicates that the user does not have the required permissions to
            create a draft Timeline.
        '409':
          content:
            application:json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: number
          description: >-
            Indicates that there is already a draft Timeline with the given
            `timelineId`.
      summary: Create a clean draft Timeline or Timeline template
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_export:
    post:
      description: Export Timelines as an NDJSON file.
      operationId: ExportTimelines
      parameters:
        - description: The name of the file to export
          in: query
          name: file_name
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  items:
                    type: string
                  nullable: true
                  type: array
        description: The IDs of the Timelines to export.
        required: true
      responses:
        '200':
          content:
            application/ndjson:
              schema:
                description: NDJSON of the exported Timelines
                type: string
          description: Indicates the Timelines were successfully exported.
        '400':
          content:
            application/ndjson:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  statusCode:
                    type: number
          description: Indicates that the export size limit was exceeded.
      summary: Export Timelines
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_favorite:
    patch:
      description: Favorite a Timeline or Timeline template for the current user.
      operationId: PersistFavoriteRoute
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                templateTimelineId:
                  nullable: true
                  type: string
                templateTimelineVersion:
                  nullable: true
                  type: number
                timelineId:
                  nullable: true
                  type: string
                timelineType:
                  $ref: '#/components/schemas/TimelineType'
                  nullable: true
              required:
                - timelineId
                - templateTimelineId
                - templateTimelineVersion
                - timelineType
        description: The required fields used to favorite a (template) Timeline.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteTimelineResponse'
          description: Indicates the favorite status was successfully updated.
        '403':
          content:
            application:json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  statusCode:
                    type: number
          description: >-
            Indicates the user does not have the required permissions to persist
            the favorite status.
      summary: Favorite a Timeline or Timeline template
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_import:
    post:
      description: Import Timelines.
      operationId: ImportTimelines
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file: {}
                isImmutable:
                  description: Whether the Timeline should be immutable
                  enum:
                    - 'true'
                    - 'false'
                  type: string
              required:
                - file
        description: The Timelines to import as a readable stream.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTimelineResult'
          description: Indicates the import of Timelines was successful.
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: Invalid file extension
                    type: string
                  statusCode:
                    example: 400
                    type: number
          description: >-
            Indicates the import of Timelines was unsuccessful because of an
            invalid file extension.
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: Unable to find saved object client
                    type: string
                  statusCode:
                    example: 404
                    type: number
          description: >-
            Indicates that we were unable to locate the saved object client
            necessary to handle the import.
        '409':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: Could not import timelines
                    type: string
                  statusCode:
                    example: 409
                    type: number
          description: Indicates the import of Timelines was unsuccessful.
      summary: Import Timelines
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/_prepackaged:
    post:
      description: Install or update prepackaged Timelines.
      operationId: InstallPrepackedTimelines
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prepackagedTimelines:
                  items:
                    $ref: '#/components/schemas/TimelineSavedToReturnObject'
                    nullable: true
                  type: array
                timelinesToInstall:
                  items:
                    $ref: '#/components/schemas/ImportTimelines'
                    nullable: true
                  type: array
                timelinesToUpdate:
                  items:
                    $ref: '#/components/schemas/ImportTimelines'
                    nullable: true
                  type: array
              required:
                - timelinesToInstall
                - timelinesToUpdate
                - prepackagedTimelines
        description: The Timelines to install or update.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTimelineResult'
          description: Indicates the installation of prepackaged Timelines was successful.
        '500':
          content:
            application:json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  statusCode:
                    type: number
          description: >-
            Indicates the installation of prepackaged Timelines was
            unsuccessful.
      summary: Install prepackaged Timelines
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timeline/resolve:
    get:
      operationId: ResolveTimeline
      parameters:
        - description: The ID of the template timeline to resolve
          in: query
          name: template_timeline_id
          schema:
            type: string
        - description: The ID of the timeline to resolve
          in: query
          name: id
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResolvedTimeline'
          description: The (template) Timeline has been found
        '400':
          description: The request is missing parameters
        '404':
          description: The (template) Timeline was not found
      summary: Get an existing saved Timeline or Timeline template
      tags:
        - Security Timeline API
        - access:securitySolution
  /api/timelines:
    get:
      description: Get a list of all saved Timelines or Timeline templates.
      operationId: GetTimelines
      parameters:
        - description: >-
            If true, only timelines that are marked as favorites by the user are
            returned.
          in: query
          name: only_user_favorite
          schema:
            enum:
              - 'true'
              - 'false'
            nullable: true
            type: string
        - in: query
          name: timeline_type
          schema:
            $ref: '#/components/schemas/TimelineType'
            nullable: true
        - in: query
          name: sort_field
          schema:
            $ref: '#/components/schemas/SortFieldTimeline'
        - description: Whether to sort the results `ascending` or `descending`
          in: query
          name: sort_order
          schema:
            enum:
              - asc
              - desc
            type: string
        - description: How many results should returned at once
          in: query
          name: page_size
          schema:
            nullable: true
            type: string
        - description: How many pages should be skipped
          in: query
          name: page_index
          schema:
            nullable: true
            type: string
        - description: Allows to search for timelines by their title
          in: query
          name: search
          schema:
            nullable: true
            type: string
        - in: query
          name: status
          schema:
            $ref: '#/components/schemas/TimelineStatus'
            nullable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  customTemplateTimelineCount:
                    description: The amount of custom Timeline templates in the results
                    example: 2
                    type: number
                  defaultTimelineCount:
                    description: The amount of `default` type Timelines in the results
                    example: 90
                    type: number
                  elasticTemplateTimelineCount:
                    description: The amount of Elastic's Timeline templates in the results
                    example: 8
                    type: number
                  favoriteCount:
                    description: The amount of favorited Timelines
                    example: 5
                    type: number
                  templateTimelineCount:
                    description: The amount of Timeline templates in the results
                    example: 10
                    type: number
                  timeline:
                    items:
                      $ref: '#/components/schemas/TimelineResponse'
                    type: array
                  totalCount:
                    description: The total amount of results
                    example: 100
                    type: number
                required:
                  - timeline
                  - totalCount
          description: Indicates that the (template) Timelines were found and returned.
        '400':
          content:
            application:json:
              schema:
                type: object
                properties:
                  body:
                    description: The error message
                    example: get timeline error
                    type: string
                  statusCode:
                    example: 405
                    type: number
          description: Bad request. The user supplied invalid data.
      summary: Get Timelines or Timeline templates
      tags:
        - Security Timeline API
        - access:securitySolution
components:
  schemas:
    AssociatedFilterType:
      description: Filter notes based on their association with a document or saved object.
      enum:
        - all
        - document_only
        - saved_object_only
        - document_and_saved_object
        - orphan
      type: string
    BareNote:
      allOf:
        - $ref: '#/components/schemas/NoteCreatedAndUpdatedMetadata'
        - type: object
          properties:
            eventId:
              description: The `_id` of the associated event for this note.
              example: d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bc
              nullable: true
              type: string
            note:
              description: The text of the note
              example: This is an example text
              nullable: true
              type: string
            timelineId:
              description: >-
                The `savedObjectId` of the Timeline that this note is associated
                with
              example: 15c1929b-0af7-42bd-85a8-56e234cc7c4e
              type: string
          required:
            - timelineId
    BarePinnedEvent:
      allOf:
        - $ref: '#/components/schemas/PinnedEventCreatedAndUpdatedMetadata'
        - type: object
          properties:
            eventId:
              description: The `_id` of the associated event for this pinned event.
              example: d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bc
              type: string
            timelineId:
              description: >-
                The `savedObjectId` of the timeline that this pinned event is
                associated with
              example: 15c1929b-0af7-42bd-85a8-56e234cc7c4e
              type: string
          required:
            - eventId
            - timelineId
    ColumnHeaderResult:
      type: object
      properties:
        aggregatable:
          nullable: true
          type: boolean
        category:
          nullable: true
          type: string
        columnHeaderType:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        example:
          nullable: true
          type: string
        id:
          nullable: true
          type: string
        indexes:
          items:
            type: string
          nullable: true
          type: array
        name:
          nullable: true
          type: string
        placeholder:
          nullable: true
          type: string
        searchable:
          nullable: true
          type: boolean
        type:
          nullable: true
          type: string
    DataProviderQueryMatch:
      type: object
      properties:
        enabled:
          nullable: true
          type: boolean
        excluded:
          nullable: true
          type: boolean
        id:
          nullable: true
          type: string
        kqlQuery:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        queryMatch:
          $ref: '#/components/schemas/QueryMatchResult'
          nullable: true
        type:
          $ref: '#/components/schemas/DataProviderType'
          nullable: true
    DataProviderResult:
      type: object
      properties:
        and:
          items:
            $ref: '#/components/schemas/DataProviderQueryMatch'
          nullable: true
          type: array
        enabled:
          nullable: true
          type: boolean
        excluded:
          nullable: true
          type: boolean
        id:
          nullable: true
          type: string
        kqlQuery:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        queryMatch:
          $ref: '#/components/schemas/QueryMatchResult'
          nullable: true
        type:
          $ref: '#/components/schemas/DataProviderType'
          nullable: true
    DataProviderType:
      description: The type of data provider.
      enum:
        - default
        - template
      type: string
    DocumentIds:
      oneOf:
        - items:
            type: string
          type: array
        - type: string
    FavoriteTimelineResponse:
      type: object
      properties:
        favorite:
          items:
            $ref: '#/components/schemas/FavoriteTimelineResult'
          type: array
        savedObjectId:
          type: string
        templateTimelineId:
          nullable: true
          type: string
        templateTimelineVersion:
          nullable: true
          type: number
        timelineType:
          $ref: '#/components/schemas/TimelineType'
        version:
          type: string
      required:
        - savedObjectId
        - version
    FavoriteTimelineResult:
      description: Indicates when and who marked a Timeline as a favorite.
      example:
        favoriteDate: 1741337636741
        userName: elastic
      type: object
      properties:
        favoriteDate:
          nullable: true
          type: number
        fullName:
          nullable: true
          type: string
        userName:
          nullable: true
          type: string
    FilterTimelineResult:
      example:
        meta:
          alias: Custom filter name
          disabled: false
          index: .alerts-security.alerts-default,logs-*
          key: '@timestamp'
          negate: false,
          type: exists
          value: exists
        query: '{"exists":{"field":"@timestamp"}}'
      type: object
      properties:
        exists:
          nullable: true
          type: string
        match_all:
          nullable: true
          type: string
        meta:
          nullable: true
          type: object
          properties:
            alias:
              nullable: true
              type: string
            controlledBy:
              nullable: true
              type: string
            disabled:
              nullable: true
              type: boolean
            field:
              nullable: true
              type: string
            formattedValue:
              nullable: true
              type: string
            index:
              nullable: true
              type: string
            key:
              nullable: true
              type: string
            negate:
              nullable: true
              type: boolean
            params:
              nullable: true
              type: string
            type:
              nullable: true
              type: string
            value:
              nullable: true
              type: string
        missing:
          nullable: true
          type: string
        query:
          nullable: true
          type: string
        range:
          nullable: true
          type: string
        script:
          nullable: true
          type: string
    GetNotesResult:
      type: object
      properties:
        notes:
          items:
            $ref: '#/components/schemas/Note'
          type: array
        totalCount:
          type: number
      required:
        - totalCount
        - notes
    ImportTimelineResult:
      type: object
      properties:
        errors:
          description: The list of failed Timeline imports
          items:
            type: object
            properties:
              error:
                description: >-
                  The error containing the reason why the timeline could not be
                  imported
                type: object
                properties:
                  message:
                    description: The reason why the timeline could not be imported
                    example: Malformed JSON
                    type: string
                  status_code:
                    description: The HTTP status code of the error
                    example: 400
                    type: number
              id:
                description: The ID of the timeline that failed to import
                example: 6ce1b592-84e3-4b4a-9552-f189d4b82075
                type: string
          type: array
        success:
          description: Indicates whether any of the Timelines were successfully imports
          type: boolean
        success_count:
          description: The amount of successfully imported/updated Timelines
          example: 99
          type: number
        timelines_installed:
          description: The amount of successfully installed Timelines
          example: 80
          type: number
        timelines_updated:
          description: The amount of successfully updated Timelines
          example: 19
          type: number
    ImportTimelines:
      allOf:
        - $ref: '#/components/schemas/SavedTimeline'
        - type: object
          properties:
            eventNotes:
              items:
                $ref: '#/components/schemas/BareNote'
              nullable: true
              type: array
            globalNotes:
              items:
                $ref: '#/components/schemas/BareNote'
              nullable: true
              type: array
            pinnedEventIds:
              items:
                type: string
              nullable: true
              type: array
            savedObjectId:
              nullable: true
              type: string
            version:
              nullable: true
              type: string
          required:
            - savedObjectId
            - version
            - pinnedEventIds
            - eventNotes
            - globalNotes
    Note:
      allOf:
        - $ref: '#/components/schemas/BareNote'
        - type: object
          properties:
            noteId:
              description: The `savedObjectId` of the note
              example: 709f99c6-89b6-4953-9160-35945c8e174e
              type: string
            version:
              description: The version of the note
              example: WzQ2LDFd
              type: string
          required:
            - noteId
            - version
    NoteCreatedAndUpdatedMetadata:
      type: object
      properties:
        created:
          description: The time the note was created, using a 13-digit Epoch timestamp.
          example: 1587468588922
          nullable: true
          type: number
        createdBy:
          description: The user who created the note.
          example: casetester
          nullable: true
          type: string
        updated:
          description: The last time the note was updated, using a 13-digit Epoch timestamp
          example: 1741344876825
          nullable: true
          type: number
        updatedBy:
          description: The user who last updated the note
          example: casetester
          nullable: true
          type: string
    PersistPinnedEventResponse:
      oneOf:
        - $ref: '#/components/schemas/PinnedEvent'
        - type: object
          properties:
            unpinned:
              description: Indicates whether the event was successfully unpinned
              type: boolean
          required:
            - unpinned
    PersistTimelineResponse:
      $ref: '#/components/schemas/TimelineResponse'
    PinnedEvent:
      allOf:
        - $ref: '#/components/schemas/BarePinnedEvent'
        - type: object
          properties:
            pinnedEventId:
              description: The `savedObjectId` of this pinned event
              example: 10r1929b-0af7-42bd-85a8-56e234f98h2f3
              type: string
            version:
              description: The version of this pinned event
              example: WzQ2LDFe
              type: string
          required:
            - pinnedEventId
            - version
    PinnedEventCreatedAndUpdatedMetadata:
      type: object
      properties:
        created:
          description: >-
            The time the pinned event was created, using a 13-digit Epoch
            timestamp.
          example: 1587468588922
          nullable: true
          type: number
        createdBy:
          description: The user who created the pinned event.
          example: casetester
          nullable: true
          type: string
        updated:
          description: >-
            The last time the pinned event was updated, using a 13-digit Epoch
            timestamp
          example: 1741344876825
          nullable: true
          type: number
        updatedBy:
          description: The user who last updated the pinned event
          example: casetester
          nullable: true
          type: string
    QueryMatchResult:
      type: object
      properties:
        displayField:
          nullable: true
          type: string
        displayValue:
          nullable: true
          type: string
        field:
          nullable: true
          type: string
        operator:
          nullable: true
          type: string
        value:
          oneOf:
            - nullable: true
              type: string
            - items:
                type: string
              nullable: true
              type: array
    ResolvedTimeline:
      type: object
      properties:
        alias_purpose:
          $ref: '#/components/schemas/SavedObjectResolveAliasPurpose'
        alias_target_id:
          type: string
        outcome:
          $ref: '#/components/schemas/SavedObjectResolveOutcome'
        timeline:
          $ref: '#/components/schemas/TimelineSavedToReturnObject'
      required:
        - timeline
        - outcome
    ResponseNote:
      type: object
      properties:
        note:
          $ref: '#/components/schemas/Note'
      required:
        - note
    RowRendererId:
      description: Identifies the available row renderers
      enum:
        - alert
        - alerts
        - auditd
        - auditd_file
        - library
        - netflow
        - plain
        - registry
        - suricata
        - system
        - system_dns
        - system_endgame_process
        - system_file
        - system_fim
        - system_security_event
        - system_socket
        - threat_match
        - zeek
      type: string
    SavedObjectIds:
      oneOf:
        - items:
            type: string
          type: array
        - type: string
    SavedObjectResolveAliasPurpose:
      enum:
        - savedObjectConversion
        - savedObjectImport
      type: string
    SavedObjectResolveOutcome:
      enum:
        - exactMatch
        - aliasMatch
        - conflict
      type: string
    SavedTimeline:
      type: object
      properties:
        columns:
          description: The Timeline's columns
          example:
            - columnHeaderType: not-filtered
              id: '@timestamp'
            - columnHeaderType: not-filtered
              id: event.category
          items:
            $ref: '#/components/schemas/ColumnHeaderResult'
          nullable: true
          type: array
        created:
          description: The time the Timeline was created, using a 13-digit Epoch timestamp.
          example: 1587468588922
          nullable: true
          type: number
        createdBy:
          description: The user who created the Timeline.
          example: casetester
          nullable: true
          type: string
        dataProviders:
          description: Object containing query clauses
          example:
            - enabled: true
              excluded: false
              id: >-
                id-d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bcbf66f57d124dcc739c98e6b
              name: d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bcbf66f57d124dcc739c98e6b
              queryMatch:
                field: _id,
                operator: ':'
                value: >-
                  d3a1d35a3e84a81b2f8f3859e064c224cdee1b4bcbf66f57d124dcc739c98e6b,
          items:
            $ref: '#/components/schemas/DataProviderResult'
          nullable: true
          type: array
        dataViewId:
          description: ID of the Timeline's Data View
          example: security-solution-default
          nullable: true
          type: string
        dateRange:
          description: The Timeline's search period.
          example:
            end: 1587456479201
            start: 1587370079200
          nullable: true
          type: object
          properties:
            end:
              oneOf:
                - nullable: true
                  type: string
                - nullable: true
                  type: number
            start:
              oneOf:
                - nullable: true
                  type: string
                - nullable: true
                  type: number
        description:
          description: The Timeline's description
          example: Investigating exposure of CVE XYZ
          nullable: true
          type: string
        eqlOptions:
          description: EQL query that is used in the correlation tab
          example:
            eventCategoryField: event.category
            query: sequence\n[process where process.name == "sudo"]\n[any where true]
            size: 100
            timestampField: '@timestamp'
          nullable: true
          type: object
          properties:
            eventCategoryField:
              nullable: true
              type: string
            query:
              nullable: true
              type: string
            size:
              oneOf:
                - nullable: true
                  type: string
                - nullable: true
                  type: number
            tiebreakerField:
              nullable: true
              type: string
            timestampField:
              nullable: true
              type: string
        eventType:
          deprecated: true
          description: Event types displayed in the Timeline
          example: all
          nullable: true
          type: string
        excludedRowRendererIds:
          description: >-
            A list of row renderers that should not be used when in `Event
            renderers` mode
          items:
            $ref: '#/components/schemas/RowRendererId'
          nullable: true
          type: array
        favorite:
          items:
            $ref: '#/components/schemas/FavoriteTimelineResult'
          nullable: true
          type: array
        filters:
          description: A list of filters that should be applied to the query
          items:
            $ref: '#/components/schemas/FilterTimelineResult'
          nullable: true
          type: array
        indexNames:
          description: >-
            A list of index names to use in the query (e.g. when the default
            data view has been modified)
          example:
            - .logs*
          items:
            type: string
          nullable: true
          type: array
        kqlMode:
          description: >-
            Indicates whether the KQL bar filters the query results or searches
            for additional results, where:
              * `filter`: filters query results
              * `search`: displays additional search results
          example: search
          nullable: true
          type: string
        kqlQuery:
          $ref: '#/components/schemas/SerializedFilterQueryResult'
          nullable: true
        savedQueryId:
          description: The ID of the saved query that might be used in the Query tab
          example: c7b16904-02d7-4f32-b8f2-cc20f9625d6e
          nullable: true
          type: string
        savedSearchId:
          description: The ID of the saved search that is used in the ES|QL tab
          example: 6ce1b592-84e3-4b4a-9552-f189d4b82075
          nullable: true
          type: string
        sort:
          $ref: '#/components/schemas/Sort'
          nullable: true
        status:
          $ref: '#/components/schemas/TimelineStatus'
          nullable: true
        templateTimelineId:
          description: >-
            A unique ID (UUID) for Timeline templates. For Timelines, the value
            is `null`.
          example: 6ce1b592-84e3-4b4a-9552-f189d4b82075
          nullable: true
          type: string
        templateTimelineVersion:
          description: >-
            Timeline template version number. For Timelines, the value is
            `null`.
          example: 12
          nullable: true
          type: number
        timelineType:
          $ref: '#/components/schemas/TimelineType'
          nullable: true
        title:
          description: The Timeline's title.
          example: CVE XYZ investigation
          nullable: true
          type: string
        updated:
          description: >-
            The last time the Timeline was updated, using a 13-digit Epoch
            timestamp
          example: 1741344876825
          nullable: true
          type: number
        updatedBy:
          description: The user who last updated the Timeline
          example: casetester
          nullable: true
          type: string
    SavedTimelineWithSavedObjectId:
      allOf:
        - $ref: '#/components/schemas/SavedTimeline'
        - type: object
          properties:
            savedObjectId:
              description: The `savedObjectId` of the Timeline or Timeline template
              example: 15c1929b-0af7-42bd-85a8-56e234cc7c4e
              type: string
            version:
              description: The version of the Timeline or Timeline template
              example: WzE0LDFd
              type: string
          required:
            - savedObjectId
            - version
    SerializedFilterQueryResult:
      description: KQL bar query.
      example:
        filterQuery: null
        kuery:
          expression: '_id : *'
          kind: kuery
        serializedQuery: >-
          {"bool":{"should":[{"exists":{"field":"_id"}}],"minimum_should_match":1}}
      type: object
      properties:
        filterQuery:
          nullable: true
          type: object
          properties:
            kuery:
              nullable: true
              type: object
              properties:
                expression:
                  nullable: true
                  type: string
                kind:
                  nullable: true
                  type: string
            serializedQuery:
              nullable: true
              type: string
    Sort:
      oneOf:
        - $ref: '#/components/schemas/SortObject'
        - items:
            $ref: '#/components/schemas/SortObject'
          type: array
    SortFieldTimeline:
      description: The field to sort the timelines by.
      enum:
        - title
        - description
        - updated
        - created
      type: string
    SortObject:
      description: Object indicating how rows are sorted in the Timeline's grid
      example:
        columnId: '@timestamp'
        sortDirection: desc
      type: object
      properties:
        columnId:
          nullable: true
          type: string
        columnType:
          nullable: true
          type: string
        sortDirection:
          nullable: true
          type: string
    TimelineResponse:
      allOf:
        - $ref: '#/components/schemas/SavedTimeline'
        - $ref: '#/components/schemas/SavedTimelineWithSavedObjectId'
        - type: object
          properties:
            eventIdToNoteIds:
              description: A list of all the notes that are associated to this Timeline.
              items:
                $ref: '#/components/schemas/Note'
              nullable: true
              type: array
            noteIds:
              description: >-
                A list of all the ids of notes that are associated to this
                Timeline.
              example:
                - 709f99c6-89b6-4953-9160-35945c8e174e
              items:
                type: string
              nullable: true
              type: array
            notes:
              description: A list of all the notes that are associated to this Timeline.
              items:
                $ref: '#/components/schemas/Note'
              nullable: true
              type: array
            pinnedEventIds:
              description: >-
                A list of all the ids of pinned events that are associated to
                this Timeline.
              example:
                - 983f99c6-89b6-4953-9160-35945c8a194f
              items:
                type: string
              nullable: true
              type: array
            pinnedEventsSaveObject:
              description: >-
                A list of all the pinned events that are associated to this
                Timeline.
              items:
                $ref: '#/components/schemas/PinnedEvent'
              nullable: true
              type: array
    TimelineSavedToReturnObject:
      allOf:
        - $ref: '#/components/schemas/SavedTimeline'
        - type: object
          properties:
            eventIdToNoteIds:
              items:
                $ref: '#/components/schemas/Note'
              nullable: true
              type: array
            noteIds:
              items:
                type: string
              nullable: true
              type: array
            notes:
              items:
                $ref: '#/components/schemas/Note'
              nullable: true
              type: array
            pinnedEventIds:
              items:
                type: string
              nullable: true
              type: array
            pinnedEventsSaveObject:
              items:
                $ref: '#/components/schemas/PinnedEvent'
              nullable: true
              type: array
            savedObjectId:
              type: string
            version:
              type: string
          required:
            - savedObjectId
            - version
    TimelineStatus:
      description: The status of the Timeline.
      enum:
        - active
        - draft
        - immutable
      type: string
    TimelineType:
      description: The type of Timeline.
      enum:
        - default
        - template
      type: string
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
security:
  - BasicAuth: []
tags:
  - description: >-
      You can create Timelines and Timeline templates via the API, as well as
      import new Timelines from an ndjson file.
    name: Security Timeline API
    x-displayName: Security timeline
